### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by AndreaEPFL** [ismailhammounou/db2ixf#44]
Package vercion 0.7.0 currently returns `TypeError: 'type' object is not subscriptable` at usage.
```python
# coding=utf-8
import pathlib
from db2ixf.ixf import IXFParser

path = pathlib.Path('Path/to/IXF/FILE/XXX.IXF')
with open(path, mode='rb') as f:
    parser = IXFParser(f)
    output_path = pathlib.Path('Path/To/Output/YYY.csv')
    with open(output_path, mode='w', encoding='utf-8') as output_file:
        parser.to_csv(output_file, sep='#')
```
returns
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from db2ixf.ixf import IXFParser
  File "db2ixf\__init__.py", line 94, in <module>
    from db2ixf.ixf import IXFParser
  File "db2ixf\ixf.py", line 11, in <module>
    from db2ixf.collectors import (collect_bigint,
  File "db2ixf\collectors.py", line 9, in <module>
    from db2ixf.helpers import get_ccsid_from_column
  File "db2ixf\helpers.py", line 10, in <module>
    def get_pyarrow_schema(cols: list[dict]) -> dict[str, object]:
TypeError: 'type' object is not subscriptable
```
If you want to maintain compatibility with Python 3.8, you need to change
https://github.com/ismailhammounou/db2ixf/blob/f6a332231dbf40baa8b21957aeafedde99c3c994/src/db2ixf/helpers.py#L10 
to
```
def get_pyarrow_schema(cols: List[dict]) -> Dict[str, object]:
```
and
https://github.com/ismailhammounou/db2ixf/blob/f6a332231dbf40baa8b21957aeafedde99c3c994/src/db2ixf/helpers.py#L84
to
```
def get_pandas_schema(cols: List[dict]) -> Dict[str, object]:
```
and
https://github.com/ismailhammounou/db2ixf/blob/f6a332231dbf40baa8b21957aeafedde99c3c994/src/db2ixf/helpers.py#L137
to
```
def merge_dicts(dicts: List[dict]) -> Dict[str, list]:
```
Thank you for the package!

**Comment by ismailhammounou** [comment]
Hi @AndreaEPFL,  

Thank you for your feedback. Problem fixed in 0.7.1.  

BR
